# Generated by Django 6.0.8 on 2026-09-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0003_add_company_id_and_missing_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='break_type',
            field=models.CharField(choices=[('tea', 'Tea Break'), ('lunch', 'Lunch Break'), ('personal', 'Personal Break'), ('job_hold', 'Job On Hold')], default='tea', max_length=20),
        ),
    ]
