# Generated by Django 5.0.14 on 2026-09-01 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '__first__'),
        ('employees', '__first__'),
        ('workforce_api', '0018_remove_walletaccount_wallet_account_type_matches_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorinvitation',
            name='initiated_by',
        ),
        migrations.AlterField(
            model_name='vendorinvitation',
            name='channel',
            field=models.CharField(choices=[('DIRECT_EMAIL', 'Direct Email'), ('MATCHING_RESULT', 'Matching Result')], default='DIRECT_EMAIL', max_length=30),
        ),
        migrations.AlterField(
            model_name='vendortechnicianrelationship',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RESIGNATION_REQUESTED', 'Resignation Requested'), ('RESIGNED', 'Resigned'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], db_index=True, default='ACTIVE', max_length=30),
        ),
        migrations.CreateModel(
            name='VendorRelievingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Resignation Requested'), ('VENDOR_APPROVED', 'Vendor Approved Dues Clearance'), ('SEVO_APPROVED', 'SEVO Admin Cleared'), ('COMPLETED', 'Completed & Relieved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', max_length=30)),
                ('reason_category', models.CharField(choices=[('TRANSITION_TO_SOLO', 'Transitioning to Independent Solo Worker'), ('RELOCATION', 'Relocation / Moving'), ('PERSONAL', 'Personal / Family Reasons'), ('RATE_DISPUTE', 'Compensation / Rate Dispute'), ('CAREER_GROWTH', 'Career Growth / Alternative Opportunities'), ('OTHER', 'Other')], default='TRANSITION_TO_SOLO', max_length=40)),
                ('resignation_notes', models.TextField(blank=True, default='')),
                ('desired_relieving_date', models.DateField(blank=True, null=True)),
                ('vendor_settlement_notes', models.TextField(blank=True, default='')),
                ('vendor_approved_at', models.DateTimeField(blank=True, null=True)),
                ('sevo_audit_notes', models.TextField(blank=True, default='')),
                ('sevo_approved_at', models.DateTimeField(blank=True, null=True)),
                ('worker_signoff_ack', models.BooleanField(default=False)),
                ('worker_signed_at', models.DateTimeField(blank=True, null=True)),
                ('vendor_signoff_ack', models.BooleanField(default=False)),
                ('vendor_signed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relieving_requests', to='workforce_api.vendortechnicianrelationship')),
                ('sevo_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_sevo_relievings', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relieving_requests', to='employees.employee')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relieving_requests', to='companies.company')),
                ('vendor_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendor_relievings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workforce_vendor_relieving_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
