# Generated by Django 5.0.14 on 2026-08-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce_api', '0019_service_skill_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceSystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workforce_system_setting',
            },
        ),
    ]
