# Generated by Django 5.0.14 on 2026-09-07 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '__first__'),
        ('employees', '__first__'),
        ('service_requests', '__first__'),
        ('workforce_api', '0022_quote_number_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkforceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('bill_to_name', models.CharField(blank=True, default='', max_length=200)),
                ('bill_to_phone', models.CharField(blank=True, default='', max_length=30)),
                ('bill_to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('bill_to_address', models.TextField(blank=True, default='')),
                ('service_category', models.CharField(blank=True, default='', max_length=150)),
                ('service_name', models.CharField(blank=True, default='', max_length=200)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inspection_fee_adjusted', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='DRAFT', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workforce_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkforceInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='OTHER', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('item_type', models.CharField(default='item', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit', models.CharField(default='unit', max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'workforce_invoice_item',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkforceInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('ONLINE', 'Online / Gateway'), ('UPI', 'UPI'), ('CARD', 'Card'), ('CASH', 'Cash on Service'), ('WALLET', 'Customer Wallet'), ('OTHER', 'Other')], default='ONLINE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='SUCCESS', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('gateway', models.CharField(blank=True, default='', max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'workforce_invoice_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workforcequote',
            name='admin_approval_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workforcequote',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workforcequote',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workforcequote',
            name='admin_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workforcequote',
            name='submitted_for_approval_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workforcequote',
            name='quote_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workforcequote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Admin Review'), ('SENT_TO_CUSTOMER', 'Sent to Customer'), ('CUSTOMER_ACCEPTED', 'Customer Accepted'), ('PENDING_ADMIN_APPROVAL', 'Pending SEVO Admin Approval'), ('ADMIN_APPROVED', 'Approved by SEVO Admin'), ('ADMIN_REJECTED', 'Rejected by SEVO Admin'), ('CHANGES_REQUESTED', 'Changes Requested'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('SUPERSEDED', 'Superseded'), ('CONVERSION_PENDING', 'Conversion Pending'), ('CONVERTED', 'Converted to Work Booking'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='workforcequote',
            constraint=models.UniqueConstraint(fields=('quote_number', 'quote_version'), name='workforce_quote_number_version_unique'),
        ),
        migrations.AddField(
            model_name='workforceinvoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_invoices', to='companies.company'),
        ),
        migrations.AddField(
            model_name='workforceinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workforceinvoice',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_invoices', to='service_requests.servicerequest'),
        ),
        migrations.AddField(
            model_name='workforceinvoice',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='workforce_api.workforcequote'),
        ),
        migrations.AddField(
            model_name='workforceinvoice',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_invoices', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='workforceinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workforce_api.workforceinvoice'),
        ),
        migrations.AddField(
            model_name='workforceinvoicepayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='workforce_api.workforceinvoice'),
        ),
        migrations.AddField(
            model_name='workforceinvoicepayment',
            name='ledger_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_invoice_payments', to='workforce_api.walletledgerentry'),
        ),
        migrations.AddField(
            model_name='workforceinvoicepayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_invoice_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workforceinvoice',
            index=models.Index(fields=['job', 'status'], name='workforce_i_job_id_1c4c58_idx'),
        ),
        migrations.AddIndex(
            model_name='workforceinvoice',
            index=models.Index(fields=['company', 'status'], name='workforce_i_company_0db1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='workforceinvoice',
            index=models.Index(fields=['customer', 'status'], name='workforce_i_custome_a0639d_idx'),
        ),
        migrations.AddIndex(
            model_name='workforceinvoicepayment',
            index=models.Index(fields=['invoice', 'status'], name='workforce_i_invoice_a4b83b_idx'),
        ),
        migrations.AddConstraint(
            model_name='workforceinvoicepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__gt', '')), fields=('invoice', 'reference'), name='workforce_invoice_payment_reference_unique'),
        ),
    ]
