# Generated by Django 5.0.14 on 2026-08-21 10:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(blank=True, default='', max_length=200)),
                ('account_number_last4', models.CharField(blank=True, default='', max_length=4)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=20)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current')], default='SAVINGS', max_length=20)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_accounts', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_accounts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendor_payout_account',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('LOCKED', 'Locked'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('lifetime_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('outstanding_recovery', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='companies.company')),
            ],
            options={
                'db_table': 'vendor_wallet',
            },
        ),
        migrations.CreateModel(
            name='VendorWalletWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', max_length=20)),
                ('payment_method', models.CharField(default='BANK_TRANSFER', max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_approved', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='companies.company')),
                ('payout_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='vendor_wallet.vendorpayoutaccount')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_processed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_requested', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='vendor_wallet.vendorwallet')),
            ],
            options={
                'db_table': 'vendor_wallet_withdrawal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(db_index=True, max_length=50)),
                ('reference_id', models.CharField(db_index=True, max_length=100)),
                ('transaction_type', models.CharField(choices=[('SERVICE_EARNING', 'Service Earning'), ('PLATFORM_COMMISSION', 'Platform Commission'), ('REFUND', 'Refund Debit'), ('RECOVERY_DEBIT', 'Recovery Debit'), ('RECOVERY_CREDIT', 'Recovery Credit'), ('WITHDRAWAL', 'Withdrawal'), ('WITHDRAWAL_REVERSAL', 'Withdrawal Reversal'), ('ADJUSTMENT_CREDIT', 'Admin Adjustment Credit'), ('ADJUSTMENT_DEBIT', 'Admin Adjustment Debit'), ('SETTLEMENT_RELEASE', 'Settlement Release'), ('REVERSAL', 'Reversal')], db_index=True, max_length=50)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING_SETTLEMENT', 'Pending Settlement'), ('REVERSED', 'Reversed'), ('FAILED', 'Failed')], db_index=True, default='COMPLETED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_rate_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_type', models.CharField(choices=[('PENDING', 'Pending'), ('AVAILABLE', 'Available')], default='AVAILABLE', max_length=20)),
                ('settlement_release_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('service_request_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('job_payment_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vendor_wallet.vendorwallet')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='vendor_wallet.vendorwalletwithdrawal')),
            ],
            options={
                'db_table': 'vendor_wallet_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorCommissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=4, help_text='Decimal fraction: 0.1000 = 10.00%. Range: 0.0000–1.0000.', max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, help_text='NULL means this rate is currently active with no expiry.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_configs', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_configs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendor_commission_config',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['company', 'is_active', 'effective_from'], name='vcc_company_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vendorcommissionconfig',
            constraint=models.CheckConstraint(check=models.Q(('commission_rate__gte', Decimal('0.0000')), ('commission_rate__lte', Decimal('1.0000'))), name='vcc_valid_commission_rate'),
        ),
        migrations.AddIndex(
            model_name='vendorwalletwithdrawal',
            index=models.Index(fields=['company', 'status'], name='vww_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorwalletwithdrawal',
            index=models.Index(fields=['wallet', '-created_at'], name='vww_wallet_created_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorwallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='vwt_wallet_created_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorwallettransaction',
            index=models.Index(fields=['transaction_type', 'status'], name='vwt_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorwallettransaction',
            index=models.Index(condition=models.Q(('status', 'PENDING_SETTLEMENT')), fields=['status', 'settlement_release_at'], name='vwt_settlement_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendorwallettransaction',
            constraint=models.UniqueConstraint(fields=('reference_type', 'reference_id'), name='vwt_idempotency_unique'),
        ),
    ]
