# Generated by Django on 2026-08-20
import uuid
from django.db import migrations, models
import django.utils.timezone


def clean_duplicate_offered_records(apps, schema_editor):
    """
    Data-cleaning step before applying the unique partial constraint:
    Finds any duplicate OFFERED records for the same (job_id, employee_id),
    keeps the newest record, and marks older duplicates as SUPERSEDED.
    """
    WorkforceJobOffer = apps.get_model("workforce_api", "WorkforceJobOffer")
    db_alias = schema_editor.connection.alias

    active_offers = (
        WorkforceJobOffer.objects.using(db_alias)
        .filter(status="OFFERED")
        .order_by("job_id", "employee_id", "-id")
    )

    seen = set()
    to_supersede_ids = []
    for offer in active_offers:
        key = (offer.job_id, offer.employee_id)
        if key in seen:
            to_supersede_ids.append(offer.id)
        else:
            seen.add(key)

    if to_supersede_ids:
        WorkforceJobOffer.objects.using(db_alias).filter(id__in=to_supersede_ids).update(
            status="SUPERSEDED",
            rejection_reason="Superseded during migration clean-up of duplicate active offers.",
        )


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("workforce_api", "0012_postserviceproof_after_presence_photo"),
    ]

    operations = [
        migrations.RunPython(clean_duplicate_offered_records, reverse_noop),
        migrations.AddField(
            model_name="workforcejoboffer",
            name="wave_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="workforcejoboffer",
            name="wave_number",
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name="workforcejoboffer",
            name="offered_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="workforcejoboffer",
            name="expires_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name="workforcejoboffer",
            constraint=models.CheckConstraint(
                **{
                    ("condition" if getattr(django, "VERSION", (5, 0)) >= (6, 0) else "check"): models.Q(("wave_number__gte", 1), ("wave_number__lte", 6)),
                    "name": "valid_wave_number_1_to_6",
                }
            ),
        ),
        migrations.AddConstraint(
            model_name="workforcejoboffer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "OFFERED")),
                fields=("job", "employee"),
                name="unique_active_job_offer_per_employee",
            ),
        ),
        migrations.AddIndex(
            model_name="workforcejoboffer",
            index=models.Index(fields=["job", "status", "expires_at"], name="wf_offer_job_st_exp_idx"),
        ),
        migrations.AddIndex(
            model_name="workforcejoboffer",
            index=models.Index(fields=["job", "wave_id", "status", "expires_at"], name="wf_offer_job_wave_idx"),
        ),
        migrations.AddIndex(
            model_name="workforcejoboffer",
            index=models.Index(fields=["employee", "status", "expires_at"], name="wf_offer_emp_st_exp_idx"),
        ),
    ]
